### ISSUE TITLE
CI system tests failing

### ISSUE THREAD

**Issue by fhinkel** [googleapis/nodejs-error-reporting#260]
I can't land my comments change only because the tests are failing: https://github.com/googleapis/nodejs-error-reporting/pull/259

```
1 failing
  1) error-reporting
       Should report unhandledRejections if enabled:
      AssertionError [ERR_ASSERTION]: Expected to find 1 error items but found 0: []
      + expected - actual
      -0
      +1
      at /tmpfs/src/github/nodejs-error-reporting/system-test/error-reporting.ts:17:34
      at Generator.next (<anonymous>)
      at fulfilled (build/system-test/error-reporting.js:15:50919)
      at <anonymous>
```

Please ping me when it's fixed and my PRs lands so I can update our documentation with the new tags.

**Comment by kinwa91** [comment]
ping @DominicKramer

**Comment by DominicKramer** [comment]
I've been able to reproduce the system test errors that state that an error event was not published to the error reporting service.  However, I was able to confirm that the error reporting library did in fact send an error event, and the event is listed in the error reporting UI.  Thus, I think the issue is that we need to increase the timeout that the tests try to get the error from the error reporting service.
