### ISSUE TITLE
flaky test "Should not report unhandledRejections if disabled"

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-error-reporting#439]
```
  1) error-reporting
       Should not report unhandledRejections if disabled:
     Uncaught DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
      at emitDeprecationWarning (internal/process/promises.js:111:13)
      at emitWarning (internal/process/promises.js:104:3)
      at emitPromiseRejectionWarnings (internal/process/promises.js:143:7)
      at process._tickCallback (internal/process/next_tick.js:69:34)

  2) error-reporting
       Should not report unhandledRejections if disabled:
     Error: done() called multiple times
  ```

see #434

**Comment by nicoleczhu** [comment]
Closing this issue as test is no longer flakey for many months
