### ISSUE TITLE
Unable to find credential information on instance when impersonating service account using gcloud auth

### ISSUE THREAD

**Issue by bhr** [googleapis/nodejs-error-reporting#643]
When using service account impersonation locally, ErrorReporting throws the following error after init:
`ERROR:@google-cloud/error-reporting: Unable to find credential information on instance. This library will be unable to communicate with the Google Cloud API to save errors.  Message: The incoming JSON object does not contain a client_email field`

The error doesn't happen when using application default credentials without service account impersonation.

#### Environment details

  - OS: macOS
  - Node.js version: v14.18.1
  - npm version: yarn 1.22.18
  - `@google-cloud/error-reporting` version: @google-cloud/error-reporting@^2.0.5

#### Steps to reproduce

  1. Run in terminal `gcloud auth application-default login \
--impersonate-service-account=<sa-id@project.iam.gserviceaccount.com>` 
  2. Start service that initiates Error Reporting, 
```
import { ErrorReporting } from '@google-cloud/error-reporting';
const errors = new ErrorReporting({ reportMode: 'always' });
…
```

**Comment by bhr** [comment]
There's a workaround using the following commands instead:
```
gcloud auth application-default login
export GOOGLE_OAUTH_ACCESS_TOKEN=$(gcloud auth print-access-token --impersonate-service-account=sa-id@project.iam.gserviceaccount.com)
```
Downside is that the token is only valid for one hour which is not ideal for local development.

While ErrorReporting is happy with that token `@google-cloud/storage` is not unfortunately.
```
error: Error: Cannot sign data without `client_email`.
    at GoogleAuth.sign (/Users/benedikt/vestico/preact-apps/node_modules/@google-cloud/storage/node_modules/google-auth-library/build/src/auth/googleauth.js:655:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sign (/Users/benedikt/vestico/preact-apps/node_modules/@google-cloud/storage/build/src/signer.js:104:35)
```

It seems google auth is expecting the service account impersonation to be done in a different way.

**Comment by bhr** [comment]
This is [probably] not the right repository. Closing the issue.
